### ISSUE TITLE
Multicast address 230.0.0.0/24 will flood Cisco switches

### ISSUE THREAD

**Issue by jmerriweather** [bitwalker/swarm#1]
On Cisco switches (and others) multicast traffic will be flooded to all ports even when IGMP snooping is enabled. Perhaps change the default/example multicast address to 230.1.1.0/24

Reference: http://www.cisco.com/c/dam/en/us/support/docs/ip/ip-multicast/ipmlt_wp.pdf, Table 3

**Comment by bitwalker** [comment]
Ah, that's great to know, I will change the default. Thanks!

**Comment by jmerriweather** [comment]
no worries 👍
