### ISSUE TITLE
Calling swarm functions on blacklisted nodes has unexpected results

### ISSUE THREAD

**Issue by arjan** [bitwalker/swarm#121]
See amongst others #92 and #31. Calling register_name, whereis_name etc. on a node that is blacklisted (or not whitelisted) gives inconsistent and wrong results.

A proposed solution is to not start a tracker process on these nodes, but instead, start a process which proxies all calls (using `:rpc.call`) to one of the tracker processes on a participating node.

@beardedeagle how does this sound?

**Comment by beardedeagle** [comment]
I'm trying to think if their may be a better way to do this.

**Comment by arjan** [comment]
Yeah.. well I have thought about this as well and I think that maybe the whole point of blacklisting / whitelisting nodes should be that *you should not use any Swarm function on those nodes*.

So maybe this actually does not need a solution. We should focus instead on #104 :-)

**Comment by arjan** [comment]
I [already wrote](https://github.com/botsquad/swarm/commit/4c435f6609dafbdda31d0020dd3bdd41acf6b3a0) the proxy solution a while back by the way. But it's hard to get the tests passing with this code, for some reason.

**Comment by beardedeagle** [comment]
> Yeah.. well I have thought about this as well and I think that maybe the whole point of blacklisting / whitelisting nodes should be that you should not use any Swarm function on those nodes.
Yeah that was kinda the way I was leaning too

> We should focus instead on #104 :-)
That is going to require some significant work. I'd be more interested in us banging out the conversion to ex_unit_clustered_case for testing so as we move into #104 we have a working test suite to hopefully catch things.

**Comment by arjan** [comment]
Yes, agreed!
