### ISSUE TITLE
Compile Warning with version 3.3.1 on Elixir 1.8.0-otp-21.2.2

### ISSUE THREAD

**Issue by OvermindDL1** [bitwalker/swarm#123]
```elixir
warning: found quoted keyword "test" but the quotes are not required. Note that keywords are always atoms, even when quoted. Similar to atoms, keywords made exclusively of Unicode letters, numbers, underscore, and @ do not require quotes
  /home/<user>/<project>/deps/swarm/mix.exs:63

==> swarm
Compiling 1 file (.erl)
Compiling 10 files (.ex)
warning: found quoted atom "nonode@nohost" but the quotes are not required. Atoms made exclusively of Unicode letters, numbers, underscore, and @ do not require quotes
  lib/swarm/tracker/tracker.ex:45

warning: variable "nclock" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/swarm/tracker/tracker.ex:854

warning: variable "nclock" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/swarm/tracker/tracker.ex:863

Generated swarm app
```
When depender project is compiling with warnings as errors it fails to build.

**Comment by arjan** [comment]
I think all of these warnings have been fixed. @bitwalker a while back we talked about baking a new release, could you do it?

@OvermindDL1 in the meantime you might consider running from master. There also have been quite a few fixes related to the tracker management.

**Comment by bitwalker** [comment]
Will do @arjan

**Comment by beardedeagle** [comment]
They are fixed . I've been on master for a bit and these don't appear @OvermindDL1. @bitwalker, @arjan is correct in asking for a new release.

**Comment by OvermindDL1** [comment]
@beardedeagle All good, I'm just updating my work CI (which is forced with warnings as errors globally) and my work doesn't like using git dependencies, either hex.pm straight or full fork, and forking for this just seems bad, so I'm waiting for the release.  :-)

**Comment by beardedeagle** [comment]
Gotcha, fair dinkum

**Comment by bitwalker** [comment]
3.4.0 is up on Hex :)

**Comment by OvermindDL1** [comment]
Woot!  Compiles clean!  Thanks much!!
