### ISSUE TITLE
Problems with example

### ISSUE THREAD

**Issue by shifters67** [bitwalker/swarm#13]
Hi Bitwalker,

apologies but i am still finding problems:

Is there a missing / in 

config :swarm,
  node_whitelist: [~r/^myapp-[\d]@.*$]

i.e. should be?
config :swarm,
  node_whitelist: [~r/^myapp-[\d]@.*$/]

Also:

  def start_worker(name) do
    {:ok, pid} = Swarm.register_name(name, MyApp.Supervisor, :register, [name])
    Swarm.join(:foo, pid)
  end

But MyApp.Supervisor does not exist as you named it 'defmodule MyApp.WorkerSup do'

It may be worth mentioning you can't test this on the same host - needs to be on 2 or more machines :-)  I was trying to run it in 2 terminal sessions and it didn't want to know.  I also got tripped by the old cookie not the same problem when i did run it across 2 machines :-)

Thanks for your work on this!

regards

Shifters

**Comment by bitwalker** [comment]
A PR was merged which updated the example, should be good to go now!
