### ISSUE TITLE
Swarm process exit callback

### ISSUE THREAD

**Issue by ostinelli** [bitwalker/swarm#134]
Hello,
I'm checking out swarm and one thing that I cannot seem to find is how to know when a registered process dies.

I could certainly set up my own monitor for the spawned processes, but this would be re-doing something that `Swarm.Tracker` is [already doing](https://github.com/bitwalker/swarm/blob/3.4.0/lib/swarm/tracker/tracker.ex#L1240), and it wouldn’t take into consideration all the handoff mechanism.

Anyone have a hint on whether this is built-in somewhere?

Thanks,
r.

**Comment by bernardo-martinez** [comment]
you can listen to the :die callback
