### ISSUE TITLE
Tests based on process groups

### ISSUE THREAD

**Issue by pdilyard** [bitwalker/swarm#14]
What is the best way to implement tests that depend on process groups? Because `Swarm.Tracker.add_meta/3` uses `GenStateMachine.cast/2`, it is possible (and frequent) for test code to run before a process has joined a group. This creates race conditions, which I've fixed for now just by using `:timer.sleep/1`. However, I don't feel that is the most practical or reliable solution, so I was wondering if there's a better way to create reliable tests.

(This is at least my theory, feel free to correct my if I'm wrong)

**Comment by pdilyard** [comment]
Update: found a better solution that I'm using for now. For future viewers:

In the test function, take advantage of the process mailbox of the `GenStateMachine` in question by sending a `call` while you wait for the `cast`. The messages are always handled in order of how they are received. `Swarm.register_name/2` sends a call to that process, so you can do this to guarantee your test doesn't move on until the mailbox is handled.

```elixir
# before
test "this one has a race condition" do
  MyProcess.start("foo") # process joins group in init function
  assert ["foo"] = Swarm.multi_call(:my_processes, :get)
end

# after
test "no race conditions here" do
  MyProcess.start("foo") # process joins group in init function
  Swarm.register_name(__MODULE__, self) # registers the test process
  assert ["foo"] = Swarm.multi_call(:my_processes, :get)
end
```

**Comment by bitwalker** [comment]
I can change `add_meta` to be a blocking operation, in retrospect it probably should be.

**Comment by pdilyard** [comment]
Perfect. That would not only fix the tests, but also fix any problems that could potentially arise in a production environment as well.
