### ISSUE TITLE
Slow startup times when running tests

### ISSUE THREAD

**Issue by pdilyard** [bitwalker/swarm#22]
When using Swarm 2.x, I noticed it would take about 2 seconds to execute `mix test` in my project, even though the tests themselves only took about 0.1 seconds to run.

When I upgraded to 3.x, this time went up to about 5 seconds.

I have a slightly modified version of the example code in the README that isolates the problem, you can see it here: https://github.com/pdilyard/swarm_performance.

1. Clone that repo
2. `mix test --only without_swarm` (starts a process using the global registry)
3. `mix test --only with_swarm` (starts a process using swarm registry)

Note how much longer it takes to register with swarm initially.

**Comment by bitwalker** [comment]
This is likely due to the cluster wait time, this can be adjusted in the configuration via `sync_nodes_timeout`. Would you mind tweaking that?

**Comment by pdilyard** [comment]
Confirmed. For anyone coming across this, I simply added this to my `config.test.exs`:

```elixir
config :swarm,
  sync_nodes_timeout: 0
```

And my tests ran in 0.02 seconds (as opposed to 5.00 seconds without that configuration).
