### ISSUE TITLE
Ubuntu 16.04 Could not start application swarm

### ISSUE THREAD

**Issue by markmeeus** [bitwalker/swarm#30]
I'm working on an umbrella app containing 1 phoenix application and 1 regular elixir application.
Swarm is used in the latter.

When developing on macos, everything works fine, but when I want to get it running on an Ubuntu 16.04, the app won't start.

These are the versions of swarm, elixir and erlang:
Swarm v 3.0.5
Elixir 1.4.1
Erlang/OTP 19

I'm getting the following output, any ideas on how to troubleshoot this? 
Could it be related to the fact that I'm running it on a single node?

```
[info] [swarm on nonode@nohost] [tracker:init] started

=INFO REPORT==== 21-Feb-2017::19:56:03 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application swarm: Swarm.start(:normal, []) returned an error: shutdown: failed to start child: Swarm.Tracker
    ** (EXIT) {:bad_return_from_init, {:state_functions, :cluster_wait, %Swarm.Tracker.TrackerState{clock: nil, nodes: [], pending_sync_reqs: [], ring: #<Ring[:nonode@nohost]>, self: :nonode@nohost, sync_node: nil, sync_ref: nil}}}
```

**Comment by bitwalker** [comment]
Could you describe more about how you are running it on Ubuntu? There is nothing OS-specific in Swarm though. Could you verify that you are running the latest version of `gen_state_machine`?

**Comment by markmeeus** [comment]
The problem went away after deleting the _build folder.
I had built the app with erlang 18, got some warnings/errors, upgraded to 19 but didn't clear the build folder.
I guess it was related to that.

**Comment by bitwalker** [comment]
Ah, yes that would do it. I'll have to keep that in mind if this comes up again. Thanks for reporting back!
