### ISSUE TITLE
Add non-swarm processes to Swarm group

### ISSUE THREAD

**Issue by thdxr** [bitwalker/swarm#41]
As the title says, is this possible? I'm testing using `Swarm.join(:test, self())` in IEx but `Swarm.members(:test)` is coming back empty.  Works fine if I register a Swarm registered process

**Comment by slashdotdash** [comment]
No, you must first register the process, using `Swarm.register_name`, before joining a group. Swarm only tracks registered processes.

**Comment by bitwalker** [comment]
@thdxr As @slashdotdash mentioned, you should register the process via Swarm if you are going to use it to track group membership. If you are just leveraging Swarm for pub/sub though, you may be better off with Phoenix Presence or `pg2`.
