### ISSUE TITLE
If nodes are not connected on application startup tracker won't sync

### ISSUE THREAD

**Issue by rosacris** [bitwalker/swarm#44]
If I start an isolated node the tracker will continue without sync, however if I connect the node to the cluster after seeing such message it will take 5 minutes to receive the registry.
With 2 process is really easy to lose the registry information
I.E.
start both nodes 1 and 2, and connect them -> start a process in node 1 -> restart node 2 and connect it after seeing the tracker without sync message -> connect node 2 -> stop node 1 any time in the next 5 minutes -> node 2 does not know about the process in node 1 and therefore no handoff is produced.

I am not sure if this is a bug or the intended functionality, is there a way to control the registry exchange frequency?

**Comment by slashdotdash** [comment]
The default [anti-entropy interval](https://github.com/bitwalker/swarm/blob/master/lib/swarm/tracker/tracker.ex#L14) is set to 5 minutes, but can be overridden by setting the following Swarm config:

```elixir
config :swarm,
  anti_entropy_interval: 60_000
```

This setting doesn't appear to be documented anywhere.

**Comment by rosacris** [comment]
Thank you for clarifying this, I'm closing the issue.
