### ISSUE TITLE
On node failure :swarm, :begin_handoff not being called

### ISSUE THREAD

**Issue by shall3790** [bitwalker/swarm#47]
i'm following the examples, when I fail a single node the process will fail over, however I can't get the :begin_handoff event with the process state.  Thanks.

**Comment by shall3790** [comment]
Actually, let me restate the question with the steps I followed:

1) Started node A, Started node B
2) created a process on node A and then I terminated node A.
3) I see the process fail over to node B and start, but no state.
4) I modify the process on node B
5) I restart node A and I see the process terminate on Node B and start this time on node A with the state!

My question: why does the process state not carry over to node b when I initially terminate node a?  And consequently why does my state go back from node b to node a when I start node a back up?  Appreciate the explanation.

**Comment by slashdotdash** [comment]
This is by design. Swarm will only use begin/end hand-off to transfer process state when moving a process between running nodes. If a process is running on a node that goes down, it's state is lost. Swarm does not track process state; you must store it externally if you need to restore it.

**Comment by shall3790** [comment]
In the use case I described, process state is being passed back to node (a) when I restart it.  This is in line with what is stated in the docs:

"easy handoff of processes between one node and another, including handoff of current process state. You may indicate whether the handoff should simply restart the process on the new node, start the process and then send it the handoff message containing state, or ignore the handoff and remain on it's current node"

We are evaluate this product for our company and its working as expected across the cluster, (distributing processes, lookup, process restart, etc).  

I'm just trying to understand the process state handoff flow.  If it's not possible, that's fine, just maybe need to change the docs or clarify how state handoff works between nodes.

**Comment by slashdotdash** [comment]
So the resolution for this issue is to clarify process state hand-off in the docs:

> Process state can be transferred between running nodes during process redistribution by using the `{:swarm, :begin_handoff}` and `{:swarm, :end_handoff, state}` callbacks. However process state will be lost when a node hosting a distributed process terminates. In this scenario you must restore the state yourself.

Does that help clarify Swarm's behaviour?

**Comment by shall3790** [comment]
Yes, thank you for the clarification.

**Comment by slashdotdash** [comment]
I've added a description of [process handoff](https://github.com/bitwalker/swarm#process-handoff) to the README.
