### ISSUE TITLE
is registery replicated?

### ISSUE THREAD

**Issue by thdxr** [bitwalker/swarm#50]
If I have 1M registrations across my cluster, does each node contain a table of all the registrations? Or is consistent hashing using to determine which node a process belongs on?

I'm trying to understand if any part of Swarm isn't fully horizontally scalable.

**Comment by slashdotdash** [comment]
Yes, the process registry is replicated amongst all nodes in the cluster. This is to support local named process lookup. 

A [`Swarm.Entry`](https://github.com/bitwalker/swarm/blob/99fe1ae5b8aaa7ed755104534efc1f3a4ed0e783/lib/swarm/tracker/entry.ex) struct is stored for each registered named process in an ETS table.

**Comment by thdxr** [comment]
So the max number of registered processes is limited by the memory of a single node in the cluster.  This probably isn't a problem for most but are the goals of Swarm not to support unlimited scalability?

**Comment by slashdotdash** [comment]
Erlang uses a mesh network to cluster nodes so there’s a limit to how many nodes you can scale to. The cost of synchronization grows with the number of node in the cluster.

The local registry is used by Swarm to provide fast process lookup, at the cost of memory required on each node.

**Comment by slashdotdash** [comment]
@bitwalker may be able to answer your question about registered process limitations and memory usage for large deployments.

**Comment by thdxr** [comment]
Exactly the cost of replication grows with every node you add.  That's why I was wondering if it's worth building a communication system that's totally dependant on consistent hashing without any replication.  Messages would be dispatched to the appropriate node and then forwarded to the right process manually.

**Comment by slashdotdash** [comment]
The consistent hash ring used by Swarm is a separate library ([libring](https://github.com/bitwalker/libring)). You could potentially use that, in conjunction with the auto cluster library ([libcluster](https://github.com/bitwalker/libcluster)), to do so. Whereas Swarm provides the process rebalancing as nodes join/leave the cluster.

**Comment by thdxr** [comment]
That's exactly what I was planning to do :) Just wanted to verify I wasn't
redoing a capability of Swarm. Thanks!

**Comment by slashdotdash** [comment]
@thdxr Good luck. 

Do take a look at the [`Swarm.Tracker` module](https://github.com/bitwalker/swarm/blob/3c5cfc5adb054aac7df36f2941ad72654ee5b338/lib/swarm/tracker/tracker.ex) for how Swarm deals with adding and removing nodes from the ring strategy.
