### ISSUE TITLE
node_whitelist and node_blacklist seem to be ignored

### ISSUE THREAD

**Issue by jerel** [bitwalker/swarm#54]
Swarm is starting processes on an iex session. My `dev` config looks like this (`prod` is using kubernetes and libcluster, the behavior happens in both):

``` elixir
iex> Application.get_all_env(:swarm)
[included_applications: [], node_blacklist: ["debug@127.0.0.1"], debug: true]
iex> Application.get_all_env(:libcluster)
[topologies: [local: [strategy: Cluster.Strategy.Epmd,
   config: [hosts: [:"app1@127.0.0.1", :"app2@127.0.0.1",
     :"app3@127.0.0.1"]]]], included_applications: []]
```
when I start the app like this: `iex --name debug@127.0.0.1 --cookie foo -S mix run` processes managed by swarm are spawned in my iex shell. (I'm running the latest from `master`)

**Comment by jerel** [comment]
I should add that the processes are started via `Swarm.register_name(name, m, f, a)`.

Also if a valid node (`app1@127.0.0.1`) is running first, `debug@127.0.0.1` joins the cluster, then `app1@127.0.0.1` is killed the processes are restarted on `debug@127.0.0.1`. I would expect them to terminate.

**Comment by slashdotdash** [comment]
Thanks for the bug report @jerel. 

Are you running the latest Swarm published on Hex (v3.0.5) or the `master` branch from GitHub?

**Comment by jerel** [comment]
We are running the latest from Hex in prod where this behavior was discovered but locally I upgraded to the latest from `master` before doing the testing documented above.

**Comment by bitwalker** [comment]
The whitelist/blacklist are regular expressions, and that may explain what's going on here. If you treat it like that, does it still occur?
