### ISSUE TITLE
Topology change stops manually registered processes on another nodes

### ISSUE THREAD

**Issue by gofoss** [bitwalker/swarm#57]
Hello!

I am using Swarm 3.0.5 with libcluster. Imagine, I have two nodes starting up.

On every node startup same procedure is invoked:
- Swarm.whereis_name to see if name is registered
- if not, start GenServer using via tuple
- try to register with Swarm.register_name/2

NodeA starts up and follows procedure and registers new process
NodeB follows same procedure, but as soon as Swarm application starts on the NodeB, before even proceeding to my custom logic, on NodeA I get the following in debug log level:

- topology change (nodeup....)
- removing registration for XXXX, nodeA is down

even though nodeA is up and after that I can run Swarm.registered/0 and see process registered on NodeB.

Any thoughts about this behavior?

Thanks!

**Comment by bitwalker** [comment]
Definitely a bug if still happening. Have you tried recent releases? Is this still an issue?

**Comment by gofoss** [comment]
I think, this was mis-configuration issue on my side. Thanks for following it up.
